stages:
    - test

test:
    stage: test
    image: golang:1.12
    script:
        - mkdir -p /go/src
        - ln -s /builds /go/src/github.com
        - go get -u github.com/mattn/go-sqlite3 github.com/jmoiron/sqlx
        - go test github.com/flimzy/anki
