# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  
  scc_job:
    runs-on: ubuntu-latest
    name: A job to count the lines of code.
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get the lines of code.
        id: scc
        uses: iryanbell/scc-docker-action@v1.0.0
        with:
          args: ${{ env.workspace }} -i js,go,html,css
  
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: Perform dependency analysis
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Depends analysis step
        uses: otrebmuh/dv8-github-action@v0.4
        id: depends
        with:
          language: 'java'
      # Use the output from the `hello` step
      - name: Depends result
        run: echo "The result of the analysis was ${{ steps.depends.outputs.result }}"
